version: '3.8'

services:
  mangaroo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    shm_size: '10gb'
    volumes:
      - ./manga_data:/app/manga_data
      - ./output:/app/output
    environment:
      - CHROMIUM_USER_DATA_DIR=/tmp/chromium
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - mangaroo-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - mangaroo-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    networks:
      - mangaroo-net

volumes:
  es_data:

networks:
  mangaroo-net:
    driver: bridge